export const categories = [
  "Beauty & Hair Care",
  "Books, Stationery & Toys",
  "Chinese Herbal Medicine / Health Food",
  "Electronics, Cellular & Photography",
  "Entertainment",
  "Fashion & Accessories",
  "Financial & Insurance",
  "Food - Restaurants, Coffee Shops & Eateries",
  "Food - Specialty",
  "Florist / Gifts",
  "Health Care Services",
  "Home Furnishings / Home Appliances",
  "Jewellery & Accessories",
  "Optical",
  "Services",
  "Shoes / Handbags / Sportswear",
  "Specialty",
  "Market",
  "Food Court",
];

export const stores = [
  "AJ Hair Salon",
  "Alana Cosmetics",
  "Cally Cosmetics",
  "Colome Nail & Lash",
  "Crystal Hair & Beauty Centre",
  "D & A Hair Salon",
  "Danny Hair Salon",
  "F10 Quick Haircut",
  "Flawsome Beauty",
  "Floy Beauty",
  "HC Express Hair Studio",
  "Kelly Hair Salon",
  "Lin Spa",
  "Minoko Nail Studio",
  "Queena Beauty Boutique",
  "Quiklaser Ltd",
  "The Hair Express",
  "Vivian Beauty Spa",
  "Yata Health & Beauty Salon",
  "Hobby JR",
  "Bill Natural Sources",
  "CanaHerbs (TCM, Herbs & Acupuncture)",
  "Gibo Health Food Ltd",
  "Gibo Health Food Ltd",
  "Ginseng World Health Food Inc.",
  "Longevita Scientific Inc.",
  "Natures Essence Health Product",
  "Nutrition Hut",
  "Whole Green Health Food",
  "Wing Hing Trading Co.Ltd",
  "Yue Wah Trading Co. Ltd",
  "28 Min Photo",
  "BBF",
  "Bell",
  "Chatr Mobile",
  "Chico Electronics",
  "China Mobile",
  "Crystal Mall Cellphone Service",
  "Crystal Repair Service Ltd",
  "E-CC Repair Centre",
  "Fido",
  "Freedom Mobile",
  "IFIX Cell Phone Repair",
  "IGT Technology Inc.",
  "Isupport Repair & Unlock Service Centre",
  "Phone Repair Centre",
  "Photo Rainbow",
  "Rogers",
  "TELUS",
  "Telecom Computers",
  "KR Multimedia",
  "Octmon",
  "Amazing Grace",
  "BQ",
  "GIALEE'S SHOWROOM",
  "My Box",
  "Radar Graph Apparel Inc",
  "Apex Insurance Services Ltd.",
  "C & C Money Transfer Corp.",
  "Can-China Financial Services Ltd.",
  "Capstone",
  "Crystal Currency Exchange",
  "Crystal Currency Exchange",
  "HAI NA XIN",
  "HIBIT Cryptoassets",
  "HSBC",
  "Kingmark (Canada) Currency Exchange",
  "Vangead Intermediary Co.",
  "Abdul V BBQ (Halal Food)",
  "Aroma Eatery",
  "Beijing BBQ House",
  "Caf Eggstatic",
  "Chewgurt Yummy",
  "Come Buy Caf",
  "Good Day Good Time",
  "Grand Crystal Seafood Restaurant",
  "Green Bamboo Vietnamese Noodle",
  "Han Ju Tofu Hot Pot",
  "Kingwu",
  "Kowloon Chinese Restaurant",
  "Marble House Eatery",
  "S & W Pepper House",
  "Shiny Tea",
  "Sunshine Caf",
  "Taan Char",
  "Wuhan Zhou Hei Ya Food Service",
  "YGF Spicy Soup",
  "Yi Fang Taiwan Fruit Tea",
  "Yunshang Rice Noodle House",
  "Misha",
  "Mountain View Food Ltd.",
  "The Boss Bakery",
  "YoHoHo Beef",
  "Zakka Supply Ltd.",
  "Amazing Grace",
  "Bona Vista",
  "Secret Garden Gifts and Flowers",
  "Tobiah Gifts & Crafts",
  "CM Dental Dr. C. Ming Hui",
  "Crystal Dental Centre",
  "Crystal Mali Pediatric Clinic",
  "Crystal Pharmacy and Medical Supplies",
  "Dr. Ng & Associates Dental Clinic",
  "Nexgen Hearing",
  "Zen Optometry",
  "Cuisine Talent",
  "Forum Home Appliances Inc.",
  "Homepoint Enterprises Inc.",
  "PFC Home Wares",
  "Things N Thanks",
  "YouNeed",
  "Fong Fong Jewellery",
  "Goldia Jewellers",
  "M & Y Jewellery Ltd.",
  "Time Square Watch & Clock Service",
  "W.W. Jewellery",
  "Wing Wah Jewellery",
  "Anthony's Optical",
  "Net Eyewear",
  "Zien Optometry",
  "4PX",
  "ABC Dry Cleaners & Alterations",
  "Adorable Pet Service Ltd",
  "Airheart International Travel",
  "Bang Bang Tang Consulting Service",
  "Best A Lock & Key, Battery & Watches",
  "Cambridge Business Group Ltd.",
  "Canadalin Consulting Inc.",
  "Chang Luck (Lottery)",
  "Choice International Consulting",
  "Choice International Consulting",
  "Cosmos Immigration & Education Corp.",
  "Crystal Gu-Zeng Center",
  "Crystal Mall Management Office",
  "EasyLuck Travel Service Ltd.",
  "Exa Gobal Marketing Inc.",
  "FSS",
  "FSS",
  "FSS",
  "FSS",
  "Fastgo Express Corp.",
  "Flower Academy of Dance",
  "Flying Parcel Service Inc.",
  "GC & Associates Professional Corporation",
  "Global Visa Consulting",
  "Gold Key Immigration Services Ltd",
  "Guangson Consulting",
  "Ignite Immigration Consulting Inc.",
  "Jensen Travel",
  "Journey West Logistic Inc.",
  "Leon Ielts",
  "Longevita",
  "M's Travel Ltd.",
  "Mei Mei Alteration And Dry Cleaners",
  "Ocean Ventures Holding Inc.",
  "Promising Immigration Consultancy Ltd.",
  "Sheng Yuan International Education & Immigration Ltd.",
  "Shipexs Counrier",
  "Silkway Travel",
  "Ucruising",
  "V.V.S.S. Consulting Ltd.",
  "Victor Immigration & Eduction Services Inc.",
  "Victor Immigration & Eduction Services Inc.",
  "Wendy Shum Notary Corporation",
  "Windsor Global Services",
  "Yu Vape",
  "eREALESTORE",
  "SE Sport",
  "Canada Bath Studio",
  "Hilton Hotel (Tiffany Ballroom)",
  "Home Textile World",
  "PCF Cartridge Depot Inc.",
  "廣緣換匯匯款公司",
  "Aunty Lee Food Ltd.",
  "CanaHerb (TCM, Herbs & Acupuncture)",
  "Datong",
  "Dim Sum King Company",
  "Dr. Bee",
  "Econowise Food Products Ltd.",
  "Fastgo Express Corp.",
  "Ginseng World Health Food Inc.",
  "Good Friend Supermarket",
  "Good Neighbour Supermarket Ltd",
  "Healthy Soyfoods",
  "Kingwuu",
  "Lok's Produce",
  "Loon Sung Foods Ltd.",
  "Pine House Bakery",
  "Seafood World",
  "Seventeen Leung Food Ent.",
  "Tai Fang Noodle Ltd.",
  "Tone Ren Hong Enterprises Ltd",
  "Top A Meat Company",
  "Whole Green Health Food",
  "Wing Hing Trading Co. Ltd.",
  "YoHoHo Beef",
  "99 BBQ House",
  "Ba Shu Sichuan Foods",
  "Bo Wah",
  "Bubble Waffle Cafe",
  "Chao Shou Wang",
  "Chef Rong Noodles",
  "Crystal Cafe",
  "Dawangong",
  "Delicious BBQ",
  "Fung May Chinese Cuisine",
  "Happy Ice House",
  "Huaxi Noodle Specialist",
  "Hung's Teppanyaki",
  "Ipoh Bean Sprout Chicken",
  "J & G Fried Chicken",
  "Kasuga",
  "Kingspark Good Food",
  "Malay Foods Ltd.",
  "Mango Charming",
  "Money Tea",
  "Morechili Bowl",
  "Mr. Yogurt",
  "Noodle House",
  "Paradise Juice & Burger",
  "Shanghai Dimsum House Ltd.",
  "Shanghai Fortune Cuisine",
  "Tea Plus",
  "Xiang Yuan Qiao Cross Bridge Rice Noodle Restaurant",
];
